[[varp]]
isServerOnly = true
id = "varp.farming_clock"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_00"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_01"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_02"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_03"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_04"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_05"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_06"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_07"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_08"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_09"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_10"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_11"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_12"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_13"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_14"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_15"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_16"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_17"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_18"
scope = "Perm"
transmit = "Never"

[[varp]]
isServerOnly = true
id = "varp.farming_patch_19"
scope = "Perm"
transmit = "Never"
