[[npc]]
id = "npc.tormented_demon_1"
inherit = "npc.tormented_demon_1"
huntMode = 0
huntRange = 0
maxRange = 30
respawnRate = 21
defaultMode = "Wander"
[npc.params]
"param.attackrate" = 6
"param.elemental_weakness_type" = 1
"param.elemental_weakness_percent" = 30
"param.tormented_demon" = 1
"param.demon" = 1
"param.cannon_immunity" = 1
"param.slayer_experience" = 1065

[[npc]]
id = "npc.tormented_demon_defenceless_1"
inherit = "npc.tormented_demon_1"

[[npc]]
id = "npc.tormented_demon_defenceless_2"
inherit = "npc.tormented_demon_2"

[[npc]]
id = "npc.tormented_demon_2"
inherit = "npc.tormented_demon_2"
huntMode = 0
huntRange = 0
maxRange = 30
respawnRate = 21
defaultMode = "Wander"
[npc.params]
"param.attackrate" = 6
"param.elemental_weakness_type" = 1
"param.elemental_weakness_percent" = 30
"param.tormented_demon" = 1
"param.demon" = 1
"param.cannon_immunity" = 1
"param.slayer_experience" = 1065
