// Adapted from oldschooljs c930f5c41da9407600541ee76020661c09e67501. See THIRD_PARTY_NOTICES.md.
package org.rsmod.content.other.treasure.trails

internal object TrailLootData {
    val tables = mapOf(
        "PrayerPageTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_s_page1"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_s_page2"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_s_page3"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_s_page4"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_z_page1"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_z_page2"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_z_page3"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_z_page4"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_g_page1"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_g_page2"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_g_page3"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_book_g_page4"),
            TrailLootEntry(1, 1, 1, item = "obj.bandos_page1"),
            TrailLootEntry(1, 1, 1, item = "obj.bandos_page2"),
            TrailLootEntry(1, 1, 1, item = "obj.bandos_page3"),
            TrailLootEntry(1, 1, 1, item = "obj.bandos_page4"),
            TrailLootEntry(1, 1, 1, item = "obj.armadyl_page1"),
            TrailLootEntry(1, 1, 1, item = "obj.armadyl_page2"),
            TrailLootEntry(1, 1, 1, item = "obj.armadyl_page3"),
            TrailLootEntry(1, 1, 1, item = "obj.armadyl_page4"),
            TrailLootEntry(1, 1, 1, item = "obj.zaros_page1"),
            TrailLootEntry(1, 1, 1, item = "obj.zaros_page2"),
            TrailLootEntry(1, 1, 1, item = "obj.zaros_page3"),
            TrailLootEntry(1, 1, 1, item = "obj.zaros_page4"),
        ), listOf()),
        "GildedTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_goldplate"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs_goldplate"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt_goldplate"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm_goldplate"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield_goldplate"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_med_helm_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_chainbody_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_sq_shield_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_2h_sword_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_spear_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.brut_rune_spear_gold"),
        ), listOf()),
        "FirelighterTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 4, 10, item = "obj.gnomish_firelighter_red"),
            TrailLootEntry(1, 4, 10, item = "obj.gnomish_firelighter_green"),
            TrailLootEntry(1, 4, 10, item = "obj.gnomish_firelighter_blue"),
            TrailLootEntry(1, 4, 10, item = "obj.trail_gnomish_firelighter_purple"),
            TrailLootEntry(1, 4, 10, item = "obj.trail_gnomish_firelighter_white"),
        ), listOf()),
        "SubTeleportScrollTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_nardah"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_mosles"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_mortton"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_feldip"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_lunarisle"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_digsite"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_piscatoris"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_pestcontrol"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_taibwo"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_lumberyard"),
            TrailLootEntry(1, 5, 15, item = "obj.scroll_charge_dragonstone"),
            TrailLootEntry(1, 5, 15, item = "obj.teleportscroll_elf"),
        ), listOf()),
        "TeleportScrollTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.bookofscrolls_empty"),
            TrailLootEntry(21, 1, 1, table = "SubTeleportScrollTable"),
        ), listOf()),
        "GiveHalfKeyTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.keyhalf2"),
            TrailLootEntry(1, 1, 1, item = "obj.keyhalf1"),
        ), listOf()),
        "BlessingTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.blessing_saradomin"),
            TrailLootEntry(1, 1, 1, item = "obj.blessing_zamorak"),
            TrailLootEntry(1, 1, 1, item = "obj.blessing_guthix"),
            TrailLootEntry(1, 1, 1, item = "obj.blessing_armadyl"),
            TrailLootEntry(1, 1, 1, item = "obj.blessing_bandos"),
            TrailLootEntry(1, 1, 1, item = "obj.blessing_zaros"),
            TrailLootEntry(7, 10000, 15000, item = "obj.coins"),
            TrailLootEntry(7, 8, 12, item = "obj.trail_sweets"),
        ), listOf()),
        "RareTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.black_2h_sword"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platebody"),
            TrailLootEntry(1, 1, 1, item = "obj.black_longsword"),
            TrailLootEntry(1, 1, 1, item = "obj.black_full_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platelegs"),
            TrailLootEntry(1, 1, 1, item = "obj.black_battleaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.black_axe"),
            TrailLootEntry(1, 1, 1, item = "obj.black_pickaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.black_plateskirt"),
            TrailLootEntry(1, 1, 1, item = "obj.black_kiteshield"),
            TrailLootEntry(1, 1, 1, item = "obj.black_med_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.black_dagger"),
            TrailLootEntry(1, 1, 1, item = "obj.black_sq_shield"),
            TrailLootEntry(1, 1, 1, item = "obj.black_chainbody"),
            TrailLootEntry(1, 1, 1, item = "obj.black_sword"),
            TrailLootEntry(1, 1, 1, item = "obj.black_mace"),
            TrailLootEntry(1, 1, 1, item = "obj.black_warhammer"),
            TrailLootEntry(1, 1, 1, item = "obj.black_scimitar"),
        ), listOf()),
        "SuccessfulUniqueTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.mole_slippers"),
            TrailLootEntry(1, 1, 1, item = "obj.frog_slippers"),
            TrailLootEntry(1, 1, 1, item = "obj.bear_slippers"),
            TrailLootEntry(1, 1, 1, item = "obj.demon_slippers"),
            TrailLootEntry(1, 1, 1, item = "obj.jester_cape"),
            TrailLootEntry(1, 1, 1, item = "obj.shoulder_parrot"),
            TrailLootEntry(1, 1, 1, item = "obj.monk_robetop_t"),
            TrailLootEntry(1, 1, 1, item = "obj.monk_robebottom_t"),
            TrailLootEntry(1, 1, 1, item = "obj.amulet_of_defence_t"),
            TrailLootEntry(1, 1, 1, item = "obj.sandwich_lady_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.sandwich_lady_top"),
            TrailLootEntry(1, 1, 1, item = "obj.sandwich_lady_bottom"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_scimitar_ornament_kit_guthix"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_scimitar_ornament_kit_saradomin"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_scimitar_ornament_kit_zamorak"),
        ), listOf()),
        "UniqueTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.cabbage"),
            TrailLootEntry(1, 1, 1, table = "SuccessfulUniqueTable"),
        ), listOf()),
        "StandardTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 5, 14, item = "obj.shrimp"),
            TrailLootEntry(1, 5, 9, item = "obj.herring"),
            TrailLootEntry(1, 5, 12, item = "obj.sardine"),
            TrailLootEntry(1, 15, 35, item = "obj.airrune"),
            TrailLootEntry(1, 15, 35, item = "obj.firerune"),
            TrailLootEntry(1, 15, 35, item = "obj.waterrune"),
            TrailLootEntry(1, 15, 35, item = "obj.earthrune"),
            TrailLootEntry(1, 15, 35, item = "obj.mindrune"),
            TrailLootEntry(1, 15, 35, item = "obj.bodyrune"),
            TrailLootEntry(1, 2, 7, item = "obj.lawrune"),
            TrailLootEntry(1, 2, 7, item = "obj.chaosrune"),
            TrailLootEntry(1, 2, 7, item = "obj.naturerune"),
            TrailLootEntry(1, 15, 30, item = "obj.bronze_arrow"),
            TrailLootEntry(1, 7, 15, item = "obj.iron_arrow"),
            TrailLootEntry(1, 1, 1, item = "obj.staff_of_air"),
            TrailLootEntry(1, 1, 1, item = "obj.staff_of_water"),
            TrailLootEntry(1, 1, 1, item = "obj.staff_of_earth"),
            TrailLootEntry(1, 1, 1, item = "obj.staff_of_fire"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_platebody"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_longsword"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_full_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_platelegs"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_battleaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_axe"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_pickaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_dagger"),
            TrailLootEntry(1, 1, 1, item = "obj.oak_shortbow"),
            TrailLootEntry(1, 1, 1, item = "obj.longbow"),
            TrailLootEntry(1, 1, 1, item = "obj.oak_longbow"),
            TrailLootEntry(1, 1, 1, item = "obj.leather_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.leather_armour"),
            TrailLootEntry(1, 1, 1, item = "obj.hardleather_body"),
            TrailLootEntry(1, 1, 1, item = "obj.leather_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.leather_cowl"),
            TrailLootEntry(1, 1, 1, item = "obj.wizards_robe"),
            TrailLootEntry(1, 1, 1, item = "obj.bluewizhat"),
            TrailLootEntry(1, 1, 1, item = "obj.black_robe"),
            TrailLootEntry(1, 1, 1, item = "obj.blackwizhat"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_plateskirt"),
            TrailLootEntry(1, 1, 1, item = "obj.shortbow"),
            TrailLootEntry(1, 1, 1, table = "RareTable"),
        ), listOf()),
        "BeginnerClueTable" to TrailLootTable(listOf(
            TrailLootEntry(11, 1, 1, table = "StandardTable"),
            TrailLootEntry(1, 1, 1, table = "UniqueTable"),
        ), listOf()),
        "BeginnerCasket" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 3, table = "BeginnerClueTable"),
        ), listOf()),
        "EasyChefTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.golden_apron"),
            TrailLootEntry(1, 1, 1, item = "obj.chefs_hat_gold"),
        ), listOf()),
        "EasySubMonkTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.monk_robetop_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.monk_robebottom_gold"),
        ), listOf()),
        "EasyMonkTable" to TrailLootTable(listOf(
            TrailLootEntry(4, 3400, 6200, item = "obj.coins"),
            TrailLootEntry(1, 1, 1, table = "EasySubMonkTable"),
        ), listOf()),
        "EasyCapeTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.wilderness_cape_zero"),
            TrailLootEntry(1, 1, 1, item = "obj.wilderness_cape_i"),
            TrailLootEntry(1, 1, 1, item = "obj.wilderness_cape_x"),
            TrailLootEntry(1, 1, 1, item = "obj.cape_of_skulls"),
        ), listOf()),
        "EasyElegantTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_male_r"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_male_r"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_female_r"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_female_r"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_male_g"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_male_g"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_female_g"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_female_g"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_male_b"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_male_b"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_female_b"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_female_b"),
        ), listOf()),
        "EasyRareTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.highwaymanmask"),
            TrailLootEntry(1, 1, 1, item = "obj.berret_blue"),
            TrailLootEntry(1, 1, 1, item = "obj.berret_black"),
            TrailLootEntry(1, 1, 1, item = "obj.berret_white"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_wig"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_flared_pants"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_pantaloons"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_sleeping_cap"),
            TrailLootEntry(1, 1, 1, item = "obj.beanie_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.imp_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.goblin_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.black_cane"),
            TrailLootEntry(1, 1, 1, item = "obj.berret_red"),
            TrailLootEntry(1, 1, 1, item = "obj.rain_bow"),
            TrailLootEntry(1, 1, 1, item = "obj.joint_of_ham"),
            TrailLootEntry(1, 1, 1, item = "obj.staff_of_bobcat"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bob_shirt_red"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bob_shirt_blue"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bob_shirt_green"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bob_shirt_black"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bob_shirt_purple"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platebody_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platelegs_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.black_plateskirt_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.black_full_helm_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.black_kiteshield_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.studded_body_trim_fur"),
            TrailLootEntry(1, 1, 1, item = "obj.studded_chaps_trim_fur"),
            TrailLootEntry(1, 1, 1, item = "obj.blue_skirt_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.wizards_robe_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.bluewizhat_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_platebody_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_platelegs_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_plateskirt_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_kiteshield_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_full_helm_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_platebody_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_platelegs_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_plateskirt_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_full_helm_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_kiteshield_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.blackwizhat_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.black_wizards_robe_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.black_skirt_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_full_helm_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_platebody_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_platelegs_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_plateskirt_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_kiteshield_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_power_ammy"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platebody_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platelegs_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.black_plateskirt_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.black_full_helm_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.black_kiteshield_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.studded_body_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.studded_chaps_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.blue_skirt_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.wizards_robe_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.bluewizhat_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_platebody_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_platelegs_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_plateskirt_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_kiteshield_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.bronze_full_helm_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_platebody_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_platelegs_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_plateskirt_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_kiteshield_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.iron_full_helm_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.blackwizhat_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.black_wizards_robe_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.black_skirt_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.wooden_shield_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_full_helm_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_platebody_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_platelegs_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_plateskirt_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_kiteshield_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.leather_armour_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.leather_chaps_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.black_heraldic_kiteshield1"),
            TrailLootEntry(1, 1, 1, item = "obj.black_heraldic_kiteshield2"),
            TrailLootEntry(1, 1, 1, item = "obj.black_heraldic_kiteshield3"),
            TrailLootEntry(1, 1, 1, item = "obj.black_heraldic_kiteshield4"),
            TrailLootEntry(1, 1, 1, item = "obj.black_heraldic_kiteshield5"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_1_black"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_2_black"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_3_black"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_4_black"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_5_black"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platebody_h1"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platebody_h2"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platebody_h3"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platebody_h4"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platebody_h5"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_robe_t"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_robe_l"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_robe_t"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_robe_l"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_robe_t"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_robe_l"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_robe_t"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_robe_l"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_robe_t"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_robe_l"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_robe_t"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_robe_l"),
            TrailLootEntry(1, 1, 1, table = "EasyChefTable"),
            TrailLootEntry(1, 1, 1, table = "EasyMonkTable"),
            TrailLootEntry(1, 1, 1, table = "EasyCapeTable"),
            TrailLootEntry(6, 1, 1, table = "EasyElegantTable"),
        ), listOf()),
        "EasyAmuletTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_amulet_of_magic"),
            TrailLootEntry(9, 1, 1, item = "obj.amulet_of_magic"),
        ), listOf()),
        "EasyBlessingsTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, table = "BlessingTable"),
            TrailLootEntry(2, 3000, 7000, item = "obj.coins"),
        ), listOf()),
        "EasyBowTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_composite_bow_willow"),
            TrailLootEntry(9, 1, 1, item = "obj.willow_longbow"),
        ), listOf()),
        "EasyStandardTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 50, 200, item = "obj.coins"),
            TrailLootEntry(1, 6, 10, item = "obj.trout"),
            TrailLootEntry(1, 6, 10, item = "obj.salmon"),
            TrailLootEntry(1, 30, 50, item = "obj.airrune"),
            TrailLootEntry(1, 30, 50, item = "obj.firerune"),
            TrailLootEntry(1, 30, 50, item = "obj.waterrune"),
            TrailLootEntry(1, 30, 50, item = "obj.earthrune"),
            TrailLootEntry(1, 30, 50, item = "obj.mindrune"),
            TrailLootEntry(1, 30, 50, item = "obj.bodyrune"),
            TrailLootEntry(1, 5, 10, item = "obj.lawrune"),
            TrailLootEntry(1, 5, 10, item = "obj.chaosrune"),
            TrailLootEntry(1, 5, 10, item = "obj.naturerune"),
            TrailLootEntry(1, 2, 6, item = "obj.trail_sweets"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platebody"),
            TrailLootEntry(1, 1, 1, item = "obj.black_longsword"),
            TrailLootEntry(1, 1, 1, item = "obj.black_full_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.black_platelegs"),
            TrailLootEntry(1, 1, 1, item = "obj.black_battleaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.black_axe"),
            TrailLootEntry(1, 1, 1, item = "obj.steel_pickaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.black_dagger"),
            TrailLootEntry(1, 1, 1, item = "obj.staff_of_air"),
            TrailLootEntry(1, 1, 1, item = "obj.studded_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.studded_body"),
            TrailLootEntry(1, 1, 1, item = "obj.willow_shortbow"),
            TrailLootEntry(1, 1, 1, item = "obj.coif"),
            TrailLootEntry(1, 1, 1, item = "obj.black_pickaxe"),
            TrailLootEntry(1, 1, 1, table = "EasyAmuletTable"),
            TrailLootEntry(1, 1, 1, table = "EasyBlessingsTable"),
            TrailLootEntry(1, 1, 1, table = "EasyBowTable"),
            TrailLootEntry(1, 1, 1, table = "PrayerPageTable"),
            TrailLootEntry(1, 1, 1, table = "FirelighterTable"),
            TrailLootEntry(1, 1, 1, table = "TeleportScrollTable"),
        ), listOf()),
        "EasyClueTable" to TrailLootTable(listOf(
            TrailLootEntry(11, 1, 1, table = "EasyStandardTable"),
            TrailLootEntry(1, 1, 1, table = "EasyRareTable"),
        ), listOf()),
        "EasyCasket" to TrailLootTable(listOf(
            TrailLootEntry(1, 2, 4, table = "EasyClueTable"),
        ), listOf(TrailTertiary(50, "obj.trail_clue_master"))),
        "MediumUnicornTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.white_unicorn_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.black_unicorn_mask"),
        ), listOf()),
        "MediumElegantTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_male_p"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_male_p"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_female_p"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_female_p"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_male"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_male"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_female"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_female"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_male_pink"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_male_pink"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_female_pink"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_female_pink"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_male_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_male_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_shirt_female_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_elegant_pants_female_gold"),
        ), listOf()),
        "MediumRareTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.boots_ranger"),
            TrailLootEntry(1, 1, 1, item = "obj.boots_wizard"),
            TrailLootEntry(1, 1, 1, item = "obj.leprechaun_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.cat_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.penguin_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_crier_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_cane"),
            TrailLootEntry(1, 1, 1, item = "obj.cabbage_shield"),
            TrailLootEntry(1, 1, 1, item = "obj.town_crier_coat"),
            TrailLootEntry(1, 1, 1, item = "obj.town_crier_bell"),
            TrailLootEntry(1, 1, 1, item = "obj.black_leprechaun_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_sandals"),
            TrailLootEntry(1, 1, 1, item = "obj.wolf_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.wolf_cloak"),
            TrailLootEntry(1, 1, 1, item = "obj.spiked_manacles"),
            TrailLootEntry(1, 1, 1, item = "obj.headband_red"),
            TrailLootEntry(1, 1, 1, item = "obj.headband_black"),
            TrailLootEntry(1, 1, 1, item = "obj.headband_brown"),
            TrailLootEntry(1, 1, 1, item = "obj.headband_white"),
            TrailLootEntry(1, 1, 1, item = "obj.headband_blue"),
            TrailLootEntry(1, 1, 1, item = "obj.headband_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.headband_pink"),
            TrailLootEntry(1, 1, 1, item = "obj.headband_green"),
            TrailLootEntry(1, 1, 1, item = "obj.strawboater_red"),
            TrailLootEntry(1, 1, 1, item = "obj.strawboater_orange"),
            TrailLootEntry(1, 1, 1, item = "obj.strawboater_green"),
            TrailLootEntry(1, 1, 1, item = "obj.strawboater_black"),
            TrailLootEntry(1, 1, 1, item = "obj.strawboater_blue"),
            TrailLootEntry(1, 1, 1, item = "obj.strawboater_pink"),
            TrailLootEntry(1, 1, 1, item = "obj.strawboater_purple"),
            TrailLootEntry(1, 1, 1, item = "obj.strawboater_white"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platebody_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platelegs_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_kiteshield_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_full_helm_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_plateskirt_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_platebody_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_platelegs_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_plateskirt_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_kiteshield_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_full_helm_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platebody_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platelegs_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_kiteshield_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_full_helm_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_plateskirt_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_platebody_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_platelegs_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_plateskirt_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_kiteshield_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.mithril_full_helm_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.climbing_boots_g"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_heraldic_kiteshield1"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_heraldic_kiteshield2"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_heraldic_kiteshield3"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_heraldic_kiteshield4"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_heraldic_kiteshield5"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_1_adamant"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_2_adamant"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_3_adamant"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_4_adamant"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_5_adamant"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platebody_h1"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platebody_h2"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platebody_h3"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platebody_h4"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platebody_h5"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonhide_body_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonhide_body_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonhide_chaps_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonhide_chaps_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_mitre"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_mitre"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_mitre"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_mitre"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_mitre"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_mitre"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_cloak"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_cloak"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_cloak"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_cloak"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_cloak"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_cloak"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_scarf"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_scarf"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_scarf"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_staff"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_staff"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_staff"),
            TrailLootEntry(1, 1, 1, item = "obj.arceuus_banner"),
            TrailLootEntry(1, 1, 1, item = "obj.piscarilius_banner"),
            TrailLootEntry(1, 1, 1, item = "obj.hosidius_banner"),
            TrailLootEntry(1, 1, 1, item = "obj.shayzien_banner"),
            TrailLootEntry(1, 1, 1, item = "obj.lovakengj_banner"),
            TrailLootEntry(1, 1, 1, table = "MediumUnicornTable"),
            TrailLootEntry(8, 1, 1, table = "MediumElegantTable"),
        ), listOf()),
        "MediumSubFirelighterTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 4, 9, item = "obj.gnomish_firelighter_red"),
            TrailLootEntry(1, 4, 9, item = "obj.gnomish_firelighter_green"),
            TrailLootEntry(1, 4, 9, item = "obj.gnomish_firelighter_blue"),
            TrailLootEntry(1, 4, 9, item = "obj.trail_gnomish_firelighter_purple"),
            TrailLootEntry(1, 4, 9, item = "obj.trail_gnomish_firelighter_white"),
        ), listOf()),
        "MediumFirelighterTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.gnomish_firelighter"),
            TrailLootEntry(9, 1, 1, table = "MediumSubFirelighterTable"),
        ), listOf()),
        "MediumAmuletTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_amulet_of_strength"),
            TrailLootEntry(9, 1, 1, item = "obj.amulet_of_power"),
        ), listOf()),
        "MediumBowTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_composite_bow_yew"),
            TrailLootEntry(9, 1, 1, item = "obj.yew_longbow"),
        ), listOf()),
        "MediumStandardTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 200, 1000, item = "obj.coins"),
            TrailLootEntry(1, 8, 12, item = "obj.lobster"),
            TrailLootEntry(1, 8, 12, item = "obj.swordfish"),
            TrailLootEntry(1, 50, 100, item = "obj.airrune"),
            TrailLootEntry(1, 50, 100, item = "obj.firerune"),
            TrailLootEntry(1, 50, 100, item = "obj.waterrune"),
            TrailLootEntry(1, 50, 100, item = "obj.earthrune"),
            TrailLootEntry(1, 50, 100, item = "obj.mindrune"),
            TrailLootEntry(1, 10, 10, item = "obj.deathrune"),
            TrailLootEntry(1, 10, 10, item = "obj.lawrune"),
            TrailLootEntry(1, 10, 10, item = "obj.chaosrune"),
            TrailLootEntry(1, 10, 10, item = "obj.naturerune"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_longsword"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_full_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platelegs"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_battleaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_axe"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_pickaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_dagger"),
            TrailLootEntry(1, 1, 1, item = "obj.adamant_platebody"),
            TrailLootEntry(1, 5, 10, item = "obj.trail_sweets"),
            TrailLootEntry(1, 1, 1, item = "obj.fire_battlestaff"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonhide_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonhide_body"),
            TrailLootEntry(1, 1, 1, item = "obj.yew_shortbow"),
            TrailLootEntry(1, 1, 1, table = "PrayerPageTable"),
            TrailLootEntry(1, 1, 1, table = "TeleportScrollTable"),
            TrailLootEntry(1, 1, 1, table = "BlessingTable"),
            TrailLootEntry(1, 1, 1, table = "MediumFirelighterTable"),
            TrailLootEntry(1, 1, 1, table = "MediumAmuletTable"),
            TrailLootEntry(1, 1, 1, table = "MediumBowTable"),
        ), listOf()),
        "MediumClueTable" to TrailLootTable(listOf(
            TrailLootEntry(10, 1, 1, table = "MediumStandardTable"),
            TrailLootEntry(1, 1, 1, table = "MediumRareTable"),
        ), listOf()),
        "MediumCasket" to TrailLootTable(listOf(
            TrailLootEntry(1, 3, 5, table = "MediumClueTable"),
        ), listOf(TrailTertiary(30, "obj.trail_clue_master"))),
        "Hard3rdageTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_torso"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_torso"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_amulet"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_silver_plate_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_silver_plate_chest"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_fighter_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_silver_plate_skirt"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_fighter_shield"),
        ), listOf()),
        "HardMegaRareTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 15, 15, item = "obj.4dose2energy"),
            TrailLootEntry(1, 15, 15, item = "obj.4dose2restore"),
            TrailLootEntry(1, 15, 15, item = "obj.4dose1antidragon"),
            TrailLootEntry(1, 1, 1, bundle = listOf("obj.4dose2attack" to 5, "obj.4dose2strength" to 5, "obj.4dose2defense" to 5)),
            TrailLootEntry(1, 1, 1, table = "Hard3rdageTable"),
            TrailLootEntry(5, 1, 1, table = "GildedTable"),
        ), listOf()),
        "HardBlessedShields" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.blessed_dhide_shield_guthix"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_dhide_shield_saradomin"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_dhide_shield_zamorak"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_dhide_shield_ancient"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_dhide_shield_armadyl"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_dhide_shield_bandos"),
        ), listOf()),
        "HardHeralicPlatebody" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_h1"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_h2"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_h3"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_h4"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_h5"),
        ), listOf()),
        "HardRareTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.robinhoodhat"),
            TrailLootEntry(1, 1, 1, item = "obj.cavalier_brown"),
            TrailLootEntry(1, 1, 1, item = "obj.cavalier_dark"),
            TrailLootEntry(1, 1, 1, item = "obj.cavalier_black"),
            TrailLootEntry(1, 1, 1, item = "obj.cavalier_white"),
            TrailLootEntry(1, 1, 1, item = "obj.cavalier_red"),
            TrailLootEntry(1, 1, 1, item = "obj.cavalier_navy"),
            TrailLootEntry(1, 1, 1, item = "obj.piratehat"),
            TrailLootEntry(1, 1, 1, item = "obj.enchanted_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.enchanted_robetop"),
            TrailLootEntry(1, 1, 1, item = "obj.enchanted_robelegs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_amulet_of_glory_4"),
            TrailLootEntry(1, 1, 1, item = "obj.pith_helmet"),
            TrailLootEntry(1, 1, 1, item = "obj.explorer_backpack"),
            TrailLootEntry(1, 1, 1, item = "obj.zombie_head"),
            TrailLootEntry(1, 1, 1, item = "obj.nunchucks"),
            TrailLootEntry(1, 1, 1, item = "obj.cyclops_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_boots_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.dual_sai"),
            TrailLootEntry(1, 1, 1, item = "obj.thieving_bag"),
            TrailLootEntry(1, 1, 1, item = "obj.rd_ornament_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.tzhaar_maul_ornament_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.beserker_necklace_ornament_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_cane"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_green"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_blue"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_red"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_black"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_1_rune"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_2_rune"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_3_rune"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_4_rune"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_heraldic_helm_5_rune"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_heraldic_kiteshield1"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_heraldic_kiteshield2"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_heraldic_kiteshield3"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_heraldic_kiteshield4"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_heraldic_kiteshield5"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_zamorak"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs_zamorak"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt_zamorak"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield_zamorak"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm_zamorak"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_chest"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_staff"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_zamorak_scarf"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_boots_zamorak"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_saradomin"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs_saradomin"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt_saradomin"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield_saradomin"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm_saradomin"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_chest"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_staff"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_saradomin_scarf"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_boots_saradomin"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_guthix"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs_guthix"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt_guthix"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield_guthix"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm_guthix"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_chest"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_staff"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_guthix_scarf"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_boots_guthix"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_bandos"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs_bandos"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt_bandos"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield_bandos"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm_bandos"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_chest"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_bandos_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_boots_bandos"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_armadyl"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs_armadyl"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt_armadyl"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield_armadyl"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm_armadyl"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_chest"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_armadyl_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_boots_armadyl"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody_ancient"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs_ancient"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt_ancient"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield_ancient"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm_ancient"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_chest"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ancient_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.blessed_boots_ancient"),
            TrailLootEntry(1, 1, 1, item = "obj.blue_dragonhide_body_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.blue_dragonhide_chaps_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.blue_dragonhide_body_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.blue_dragonhide_chaps_trim_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.red_dragonhide_body_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.red_dragonhide_chaps_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.red_dragonhide_body_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.red_dragonhide_chaps_gold"),
            TrailLootEntry(1, 1, 1, table = "HardMegaRareTable"),
            TrailLootEntry(1, 1, 1, table = "HardBlessedShields"),
            TrailLootEntry(1, 1, 1, table = "HardHeralicPlatebody"),
        ), listOf()),
        "HardBowTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_composite_bow_magic"),
            TrailLootEntry(9, 1, 1, item = "obj.magic_longbow"),
        ), listOf()),
        "HardStandardTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1000, 5000, item = "obj.coins"),
            TrailLootEntry(1, 12, 15, item = "obj.lobster"),
            TrailLootEntry(1, 12, 15, item = "obj.shark"),
            TrailLootEntry(1, 30, 50, item = "obj.lawrune"),
            TrailLootEntry(1, 20, 30, item = "obj.bloodrune"),
            TrailLootEntry(1, 30, 50, item = "obj.naturerune"),
            TrailLootEntry(1, 7, 15, item = "obj.trail_sweets"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_longsword"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_full_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_battleaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_axe"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_pickaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_dagger"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield"),
            TrailLootEntry(1, 1, 1, item = "obj.black_dragonhide_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.black_dragonhide_body"),
            TrailLootEntry(1, 1, 1, item = "obj.magic_shortbow"),
            TrailLootEntry(1, 1, 1, table = "PrayerPageTable"),
            TrailLootEntry(1, 1, 1, table = "FirelighterTable"),
            TrailLootEntry(1, 1, 1, table = "TeleportScrollTable"),
            TrailLootEntry(1, 1, 1, table = "BlessingTable"),
            TrailLootEntry(1, 1, 1, table = "HardBowTable"),
        ), listOf()),
        "HardClueTable" to TrailLootTable(listOf(
            TrailLootEntry(12, 1, 1, table = "HardStandardTable"),
            TrailLootEntry(1, 1, 1, table = "HardRareTable"),
        ), listOf()),
        "HardCasket" to TrailLootTable(listOf(
            TrailLootEntry(1, 4, 6, table = "HardClueTable"),
        ), listOf(TrailTertiary(15, "obj.trail_clue_master"))),
        "Elite3rdageTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_torso"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_torso"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_amulet"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_silver_plate_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_silver_plate_chest"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_fighter_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_silver_plate_skirt"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_fighter_shield"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_fighter_sword"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_third_cape"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_wand"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_bow"),
        ), listOf()),
        "EliteMegaRareTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.rune_scimitar_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_boots_gold"),
            TrailLootEntry(1, 100, 100, item = "obj.battlestaff"),
            TrailLootEntry(1, 1, 1, item = "obj.crystal_key"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_lava"),
            TrailLootEntry(1, 30, 30, item = "obj.4doserangerspotion"),
            TrailLootEntry(1, 30, 30, item = "obj.4dosepotionofsaradomin"),
            TrailLootEntry(1, 30, 30, item = "obj.4dose2restore"),
            TrailLootEntry(1, 1, 1, item = "obj.ring_of_nature"),
            TrailLootEntry(1, 30, 30, item = "obj.4dose2antidragon"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_dhide_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_dhide_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_dhide_top"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_dhide_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_pickaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_axe"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_spade"),
            TrailLootEntry(5, 1, 1, table = "GildedTable"),
            TrailLootEntry(1, 1, 1, table = "Elite3rdageTable"),
        ), listOf()),
        "EliteTuxedoTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_body"),
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_hands"),
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_feet"),
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_bowtie"),
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_body_white"),
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_hands_white"),
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_legs_white"),
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_feet_white"),
            TrailLootEntry(1, 1, 1, item = "obj.tuxedo_bowtie_white"),
        ), listOf()),
        "EliteRareTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.dragon_cane"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_briefcase"),
            TrailLootEntry(1, 1, 1, item = "obj.wise_spectacles"),
            TrailLootEntry(1, 1, 1, item = "obj.royal_crown"),
            TrailLootEntry(1, 1, 1, item = "obj.royal_sceptre"),
            TrailLootEntry(1, 1, 1, item = "obj.royal_top"),
            TrailLootEntry(1, 1, 1, item = "obj.royal_bottom"),
            TrailLootEntry(1, 1, 1, item = "obj.fury_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_chainbody_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_platelegs_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_sq_shield_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_full_helm_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_bronze"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_iron"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_steel"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_mith"),
            TrailLootEntry(1, 1, 1, item = "obj.afro"),
            TrailLootEntry(1, 1, 1, item = "obj.katana"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_pirate_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.top_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.light_inf_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.dark_inf_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.black_dragonhide_chaps_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.black_dragonhide_chaps_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.black_dragonhide_body_trim"),
            TrailLootEntry(1, 1, 1, item = "obj.black_dragonhide_body_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.musketeer_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.musketeer_top"),
            TrailLootEntry(1, 1, 1, item = "obj.musketeer_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.deerstalker"),
            TrailLootEntry(1, 1, 1, item = "obj.blacksmith_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_scarf_arceuus"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_scarf_hosidius"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_scarf_lovakengj"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_scarf_piscarilius"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_scarf_shayzien"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_scimitar_ornament_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.holy_wraps"),
            TrailLootEntry(1, 1, 1, item = "obj.ranger_gloves"),
            TrailLootEntry(1, 1, 1, item = "obj.bucket_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.fremennik_kilt"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_adamant"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonmask_rune"),
            TrailLootEntry(1, 1, 1, item = "obj.rangers_tights"),
            TrailLootEntry(1, 1, 1, item = "obj.uris_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.giant_boot"),
            TrailLootEntry(1, 1, 1, item = "obj.ranger_tunic"),
            TrailLootEntry(1, 1, 1, item = "obj.monacle"),
            TrailLootEntry(2, 1, 1, table = "EliteMegaRareTable"),
            TrailLootEntry(1, 1, 1, table = "EliteTuxedoTable"),
        ), listOf()),
        "EliteSeedTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.magic_tree_seed"),
            TrailLootEntry(1, 1, 1, item = "obj.yew_seed"),
            TrailLootEntry(1, 1, 1, item = "obj.palm_tree_seed"),
        ), listOf()),
        "EliteStandardTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 20000, 30000, item = "obj.coins"),
            TrailLootEntry(1, 15, 20, item = "obj.potato_tuna+sweetcorn"),
            TrailLootEntry(1, 15, 20, item = "obj.summer_pie"),
            TrailLootEntry(1, 50, 75, item = "obj.lawrune"),
            TrailLootEntry(1, 50, 75, item = "obj.deathrune"),
            TrailLootEntry(1, 50, 75, item = "obj.bloodrune"),
            TrailLootEntry(1, 50, 75, item = "obj.soulrune"),
            TrailLootEntry(1, 60, 80, item = "obj.plank_oak"),
            TrailLootEntry(1, 9, 23, item = "obj.trail_sweets"),
            TrailLootEntry(1, 40, 50, item = "obj.plank_teak"),
            TrailLootEntry(1, 20, 30, item = "obj.plank_mahogany"),
            TrailLootEntry(1, 1, 1, item = "obj.jewl_dragonstone_bracelet"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonstone_necklace"),
            TrailLootEntry(1, 1, 1, item = "obj.dragonstone_ring"),
            TrailLootEntry(1, 1, 3, item = "obj.runite_bar"),
            TrailLootEntry(1, 8, 12, item = "obj.xbows_bolt_tips_onyx"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_dagger"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_longsword"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platebody"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_platelegs"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_plateskirt"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_kiteshield"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_mace"),
            TrailLootEntry(1, 1, 1, item = "obj.xbows_crossbow_runite"),
            TrailLootEntry(1, 1, 1, table = "EliteSeedTable"),
            TrailLootEntry(1, 1, 1, table = "PrayerPageTable"),
            TrailLootEntry(1, 1, 1, table = "FirelighterTable"),
            TrailLootEntry(1, 1, 1, table = "GiveHalfKeyTable"),
            TrailLootEntry(2, 1, 1, table = "TeleportScrollTable"),
            TrailLootEntry(1, 1, 1, table = "BlessingTable"),
        ), listOf()),
        "EliteClueTable" to TrailLootTable(listOf(
            TrailLootEntry(24, 1, 1, table = "EliteStandardTable"),
            TrailLootEntry(1, 1, 1, table = "EliteRareTable"),
        ), listOf()),
        "EliteCasket" to TrailLootTable(listOf(
            TrailLootEntry(1, 4, 6, table = "EliteClueTable"),
        ), listOf(TrailTertiary(5, "obj.trail_clue_master"))),
        "MasterGodSwordOrnTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.ags_ornament_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.bgs_ornament_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.zgs_ornament_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.sgs_ornament_kit"),
        ), listOf()),
        "MasterSubAnkouOutfitTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.ankou_head"),
            TrailLootEntry(1, 1, 1, item = "obj.ankou_body"),
            TrailLootEntry(1, 1, 1, item = "obj.ankou_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.ankou_hands"),
            TrailLootEntry(1, 1, 1, item = "obj.ankou_feet"),
        ), listOf()),
        "MasterAnkouOutfitTable" to TrailLootTable(listOf(
            TrailLootEntry(2, 15000, 30000, item = "obj.coins"),
            TrailLootEntry(1, 1, 1, table = "MasterSubAnkouOutfitTable"),
        ), listOf()),
        "MasterSubMummyOutfitTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.mummy_head"),
            TrailLootEntry(1, 1, 1, item = "obj.mummy_body"),
            TrailLootEntry(1, 1, 1, item = "obj.mummy_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.mummy_hands"),
            TrailLootEntry(1, 1, 1, item = "obj.mummy_feet"),
        ), listOf()),
        "MasterMummyOutfitTable" to TrailLootTable(listOf(
            TrailLootEntry(2, 15000, 30000, item = "obj.coins"),
            TrailLootEntry(1, 1, 1, table = "MasterSubMummyOutfitTable"),
        ), listOf()),
        "MasterSubDragonOrnTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.dragon_kiteshield_kit"),
            TrailLootEntry(2, 1, 1, item = "obj.dragon_platebody_kit"),
        ), listOf()),
        "MasterDragonOrnTable" to TrailLootTable(listOf(
            TrailLootEntry(9, 15000, 30000, item = "obj.coins"),
            TrailLootEntry(1, 1, 1, table = "MasterSubDragonOrnTable"),
        ), listOf()),
        "Master3rdageTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_torso"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_torso"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_amulet"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_silver_plate_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_silver_plate_chest"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_fighter_helm"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_silver_plate_skirt"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_fighter_shield"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_fighter_sword"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_third_cape"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_mage_wand"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_ranger_bow"),
            TrailLootEntry(1, 1, 1, item = "obj.3a_druidic_staff"),
            TrailLootEntry(1, 1, 1, item = "obj.3a_druidic_cloak"),
            TrailLootEntry(1, 1, 1, item = "obj.3a_druidic_top"),
            TrailLootEntry(1, 1, 1, item = "obj.3a_druidic_bottoms"),
            TrailLootEntry(1, 1, 1, item = "obj.3a_pickaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.3a_axe"),
        ), listOf()),
        "MasterMegaRareTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.rune_scimitar_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.bucket_helm_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.rune_boots_gold"),
            TrailLootEntry(1, 1, 1, item = "obj.ring_of_coins"),
            TrailLootEntry(1, 3, 3, item = "obj.cabbage"),
            TrailLootEntry(1, 15, 15, item = "obj.antivenom+4"),
            TrailLootEntry(1, 50, 50, item = "obj.torstol"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_dhide_coif"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_dhide_vambraces"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_dhide_top"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_dhide_chaps"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_pickaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_axe"),
            TrailLootEntry(1, 1, 1, item = "obj.trail_gilded_spade"),
            TrailLootEntry(1, 1, 1, table = "Master3rdageTable"),
            TrailLootEntry(1, 1, 1, table = "GildedTable"),
        ), listOf()),
        "MasterRareTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 1, item = "obj.eye_patch_02"),
            TrailLootEntry(1, 1, 1, item = "obj.the_bowl"),
            TrailLootEntry(1, 1, 1, item = "obj.ale_gods"),
            TrailLootEntry(1, 1, 1, item = "obj.half_moon_spectacles"),
            TrailLootEntry(1, 1, 1, item = "obj.fancy_tiara"),
            TrailLootEntry(1, 1, 1, item = "obj.robe_darkness_head"),
            TrailLootEntry(1, 1, 1, item = "obj.robe_darkness_top"),
            TrailLootEntry(1, 1, 1, item = "obj.robe_darkness_hands"),
            TrailLootEntry(1, 1, 1, item = "obj.robe_darkness_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.robe_darkness_feet"),
            TrailLootEntry(1, 1, 1, item = "obj.tzhaar_cape_obsidian_r"),
            TrailLootEntry(1, 1, 1, item = "obj.occult_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.torture_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.dd_ornament_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.samurai_hat"),
            TrailLootEntry(1, 1, 1, item = "obj.samurai_top"),
            TrailLootEntry(1, 1, 1, item = "obj.samurai_legs"),
            TrailLootEntry(1, 1, 1, item = "obj.samurai_boots"),
            TrailLootEntry(1, 1, 1, item = "obj.samurai_gloves"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_hood_arceuus"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_hood_hosidius"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_hood_lovakengj"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_hood_piscarilius"),
            TrailLootEntry(1, 1, 1, item = "obj.zeah_hood_shayzien"),
            TrailLootEntry(1, 1, 1, item = "obj.lesser_demon_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.greater_demon_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.black_demon_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.jungle_demon_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.old_demon_mask"),
            TrailLootEntry(1, 1, 1, item = "obj.anguish_kit"),
            TrailLootEntry(1, 1, 1, item = "obj.tormented_kit"),
            TrailLootEntry(1, 1, 1, table = "MasterMegaRareTable"),
            TrailLootEntry(1, 1, 1, table = "PrayerPageTable"),
            TrailLootEntry(1, 1, 1, table = "MasterGodSwordOrnTable"),
            TrailLootEntry(1, 1, 1, table = "MasterAnkouOutfitTable"),
            TrailLootEntry(1, 1, 1, table = "MasterMummyOutfitTable"),
            TrailLootEntry(1, 1, 1, table = "MasterDragonOrnTable"),
        ), listOf()),
        "MasterSeedTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 1, 2, item = "obj.magic_tree_seed"),
            TrailLootEntry(1, 1, 2, item = "obj.yew_seed"),
            TrailLootEntry(1, 1, 2, item = "obj.palm_tree_seed"),
        ), listOf()),
        "MasterStandardTable" to TrailLootTable(listOf(
            TrailLootEntry(1, 20000, 35000, item = "obj.coins"),
            TrailLootEntry(1, 15, 25, item = "obj.mantaray"),
            TrailLootEntry(1, 100, 200, item = "obj.naturerune"),
            TrailLootEntry(1, 100, 200, item = "obj.deathrune"),
            TrailLootEntry(1, 100, 200, item = "obj.bloodrune"),
            TrailLootEntry(1, 100, 200, item = "obj.soulrune"),
            TrailLootEntry(1, 40, 60, item = "obj.limpwurt_root"),
            TrailLootEntry(1, 14, 33, item = "obj.trail_sweets"),
            TrailLootEntry(1, 5, 8, item = "obj.runite_ore"),
            TrailLootEntry(1, 35, 50, item = "obj.wine_of_zamorak"),
            TrailLootEntry(1, 25, 35, item = "obj.unidentified_toadflax"),
            TrailLootEntry(1, 5, 10, item = "obj.unidentified_ranarr"),
            TrailLootEntry(1, 5, 10, item = "obj.unidentified_snapdragon"),
            TrailLootEntry(1, 5, 7, item = "obj.runite_bar"),
            TrailLootEntry(1, 15, 25, item = "obj.xbows_crossbow_bolts_runite_tipped_onyx_enchanted"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_dagger"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_longsword"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_battleaxe"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_scimitar"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_halberd"),
            TrailLootEntry(1, 5, 25, item = "obj.dragonhide_black"),
            TrailLootEntry(1, 1, 1, item = "obj.dragon_mace"),
            TrailLootEntry(1, 1, 1, table = "PrayerPageTable"),
            TrailLootEntry(1, 1, 1, table = "FirelighterTable"),
            TrailLootEntry(2, 1, 1, table = "TeleportScrollTable"),
            TrailLootEntry(1, 1, 1, table = "MasterSeedTable"),
            TrailLootEntry(1, 1, 1, table = "GiveHalfKeyTable"),
            TrailLootEntry(1, 1, 1, table = "BlessingTable"),
        ), listOf()),
        "MasterClueTable" to TrailLootTable(listOf(
            TrailLootEntry(22, 1, 1, table = "MasterStandardTable"),
            TrailLootEntry(1, 1, 1, table = "MasterRareTable"),
        ), listOf()),
        "MasterCasket" to TrailLootTable(listOf(
            TrailLootEntry(1, 5, 7, table = "MasterClueTable"),
        ), listOf(TrailTertiary(1000, "obj.bloodhound_pet"))),
    )
}
