package org.rsmod.content.other.npc.animations

// Generated from tools/npc-animations/lifecycle-profiles.json.
internal object NpcAnimationDeathProfiles {
    val sequences: Map<String, List<String>> = mapOf(
        "npc.tob_xarpus_combat" to listOf("seq.tob_xarpus_death_a", "seq.tob_xarpus_death_b"),
        "npc.tob_maiden_100" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_70" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_50" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_30" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_dying_a" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_dying_b" to listOf("seq.maiden_death_b"),
        "npc.jormungand" to listOf("seq.jormungand_death_part_1", "seq.jormungand_death_part_2"),
        "npc.tob_xarpus_combat_story" to listOf("seq.tob_xarpus_death_a", "seq.tob_xarpus_death_b"),
        "npc.tob_xarpus_combat_hard" to listOf("seq.tob_xarpus_death_a", "seq.tob_xarpus_death_b"),
        "npc.tob_maiden_100_story" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_70_story" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_50_story" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_30_story" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_dying_a_story" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_dying_b_story" to listOf("seq.maiden_death_b"),
        "npc.tob_maiden_100_hard" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_70_hard" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_50_hard" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_30_hard" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_dying_a_hard" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.tob_maiden_dying_b_hard" to listOf("seq.maiden_death_b"),
        "npc.myq6_maiden_100" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.myq6_maiden_70" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.myq6_maiden_50" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.myq6_maiden_30" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.myq6_maiden_dying_a" to listOf("seq.maiden_death_a", "seq.maiden_death_b"),
        "npc.myq6_maiden_dying_b" to listOf("seq.maiden_death_b"),
        "npc.maggot_king" to listOf("seq.npc_maggot_king_death_01", "seq.npc_maggot_king_death_02", "seq.npc_maggot_king_death_03"),
    )
    val forms = mapOf(
        "npc.tob_maiden_100" to listOf("npc.tob_maiden_dying_a", "npc.tob_maiden_dying_b"),
        "npc.tob_maiden_70" to listOf("npc.tob_maiden_dying_a", "npc.tob_maiden_dying_b"),
        "npc.tob_maiden_50" to listOf("npc.tob_maiden_dying_a", "npc.tob_maiden_dying_b"),
        "npc.tob_maiden_30" to listOf("npc.tob_maiden_dying_a", "npc.tob_maiden_dying_b"),
        "npc.tob_maiden_dying_a" to listOf("npc.tob_maiden_dying_a", "npc.tob_maiden_dying_b"),
        "npc.tob_maiden_dying_b" to listOf("npc.tob_maiden_dying_b"),
        "npc.tob_maiden_100_story" to listOf("npc.tob_maiden_dying_a_story", "npc.tob_maiden_dying_b_story"),
        "npc.tob_maiden_70_story" to listOf("npc.tob_maiden_dying_a_story", "npc.tob_maiden_dying_b_story"),
        "npc.tob_maiden_50_story" to listOf("npc.tob_maiden_dying_a_story", "npc.tob_maiden_dying_b_story"),
        "npc.tob_maiden_30_story" to listOf("npc.tob_maiden_dying_a_story", "npc.tob_maiden_dying_b_story"),
        "npc.tob_maiden_dying_a_story" to listOf("npc.tob_maiden_dying_a_story", "npc.tob_maiden_dying_b_story"),
        "npc.tob_maiden_dying_b_story" to listOf("npc.tob_maiden_dying_b_story"),
        "npc.tob_maiden_100_hard" to listOf("npc.tob_maiden_dying_a_hard", "npc.tob_maiden_dying_b_hard"),
        "npc.tob_maiden_70_hard" to listOf("npc.tob_maiden_dying_a_hard", "npc.tob_maiden_dying_b_hard"),
        "npc.tob_maiden_50_hard" to listOf("npc.tob_maiden_dying_a_hard", "npc.tob_maiden_dying_b_hard"),
        "npc.tob_maiden_30_hard" to listOf("npc.tob_maiden_dying_a_hard", "npc.tob_maiden_dying_b_hard"),
        "npc.tob_maiden_dying_a_hard" to listOf("npc.tob_maiden_dying_a_hard", "npc.tob_maiden_dying_b_hard"),
        "npc.tob_maiden_dying_b_hard" to listOf("npc.tob_maiden_dying_b_hard"),
        "npc.myq6_maiden_100" to listOf("npc.myq6_maiden_dying_a", "npc.myq6_maiden_dying_b"),
        "npc.myq6_maiden_70" to listOf("npc.myq6_maiden_dying_a", "npc.myq6_maiden_dying_b"),
        "npc.myq6_maiden_50" to listOf("npc.myq6_maiden_dying_a", "npc.myq6_maiden_dying_b"),
        "npc.myq6_maiden_30" to listOf("npc.myq6_maiden_dying_a", "npc.myq6_maiden_dying_b"),
        "npc.myq6_maiden_dying_a" to listOf("npc.myq6_maiden_dying_a", "npc.myq6_maiden_dying_b"),
        "npc.myq6_maiden_dying_b" to listOf("npc.myq6_maiden_dying_b"),
    )
}
