package org.rsmod.content.other.npc.animations

// Non-retaliating native props; keep native incoming damage, death and rewards.
internal object NpcAnimationStaticProfiles {
    val targets = setOf(
        "npc.poh_combat_dummy_npc",
        "npc.test_combat_dummy",
        "npc.poh_combat_dummy_undeadslayer_npc",
        "npc.test_combat_dummy_maxhit",
        "npc.poh_combat_dummy_upgraded_npc",
        "npc.poh_combat_dummy_upgraded_undeadslayer_npc",
        "npc.poh_combat_dummy_upgraded_ether_npc",
        "npc.poh_combat_dummy_upgraded_kq_npc",
        "npc.poh_combat_dummy_upgraded_kurask_npc",
        "npc.poh_combat_dummy_upgraded_vampire_npc",
        "npc.poh_combat_dummy_upgraded_vorkath_npc",
        "npc.dps_calc_npc_sea",
        "npc.test_combat_dummy_2",
        "npc.castlewars_barricade_saradomin",
        "npc.castlewars_barricade_zamorak",
        "npc.castlewars_barricade_burning_saradomin",
        "npc.castlewars_barricade_burning_zamorak",
        "npc.castlewars_barricade_saradomin_render_under",
        "npc.castlewars_barricade_zamorak_render_under",
        "npc.castlewars_barricade_burning_saradomin_render_under",
        "npc.castlewars_barricade_burning_zamorak_render_under",
        "npc.soul_wars_barricade_blue",
        "npc.soul_wars_barricade_red",
        "npc.verzik_web_npc",
        "npc.verzik_web_npc_story",
        "npc.verzik_web_npc_hard",
        "npc.raids_vespula_portal",
        "npc.raids_vasanistirio_crystal",
        "npc.shayzienquest_puzzle_piece",
        "npc.lanscape_mole_sticky_mud_npc",
        "npc.pest_portal_1_active",
        "npc.pest_portal_2_active",
        "npc.pest_portal_3_active",
        "npc.pest_portal_4_active",
        "npc.pest_portal_1_active_bt1",
        "npc.pest_portal_2_active_bt1",
        "npc.pest_portal_3_active_bt1",
        "npc.pest_portal_4_active_bt1",
        "npc.hespori_healer_active",
        "npc.tobquest_hespori_healer_active",
    )
}
